### ISSUE TITLE
WMS services for HF radar data from NDBC

### ISSUE THREAD

**Issue by robragsdale** [ioos/HF-radar#1]
There is a lack of WMS servicees at NDBC for HF radar data.  
http://sdf.ndbc.noaa.gov:8080/thredds/catalog.html?dataset=hfradar_usegc_6km.  Can NDBC turn on their WMS on their THREDDS server? Is there a reason it is turned off or is it by default?  I will contact NDBC to see if the service can be enabled.

**Comment by rsignell-usgs** [comment]
oops, I'm closing this because it's superceded by #2.

**Comment by robragsdale** [comment]
Rich, I realized that was the case.  Thanks for following-up.
